language: cpp

sudo: required
dist: trusty

os: linux
compiler: gcc

env:
  - BUILD_TYPE=Release \
    CC_COMPILER=gcc-8 \
    CXX_COMPILER=g++-8 \
    ENABLE_TESTING=TRUE

addons:
  apt:
    packages:
      - gcc-8
      - g++-8
    sources:
      - ubuntu-toolchain-r-test

install:
  # Set up environment variables.
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}

  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"

  - CMAKE_VERSION=3.10.0
  - CMAKE_ARCH=cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
  - CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION::-2}/${CMAKE_ARCH}"
  - mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - sudo pip install conan

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - |
    conan install .. --build=missing \
      -s build_type=${BUILD_TYPE} \
      -s compiler.libcxx=libstdc++14
    - |
      cmake .. \
        -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
        -DENABLE_TESTING:BOOL=${ENABLE_TESTING}
    - cmake --build . --config ${BUILD_TYPE} -- -j2